version: '2'

services:
  jenkins:
    build: .
    image: jenkins_docker
    container_name: jenkins_dock
    networks:
      jenkins2_net:
        aliases:
          - jenkins_docker
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /development/repos/jenkins-docker/hpi:/var/jenkins_home/plugins
    #Add host docker group to jenkins container user (needed for docker in docker)
    group_add:
      - ${DOCKER_HOST_GROUP_ID}
     
volumes:
  jenkins_data:
    external: true

networks:
  jenkins2_net:
    external: true